### ISSUE TITLE
Missing alpha channel

### ISSUE THREAD

**Issue by forstjiri** [NC22/HTML5-Color-Picker#1]
This color picker seems great, except missing option for transparency, would be possible to add a transparency slider?

**Comment by NC22** [comment]
Yep. Thats possible, but I dont have much time for work around that at current moment. I'll upload beta version with simple transparancy slider today when its ready.

**Comment by NC22** [comment]
Ok, so new release here 

https://github.com/NC22/HTML5-Color-Picker/releases
see example with enabled slider
test_resize_onchange_event.html

some new enter methods, etc. later will add to wiki

new constructor parameters

alpha -  base value for alpha (float value from 0 to 1) default 1
alpha_slider - enable alpha slider (boolean) default false

new events

mouseupalpha
mousemovealpha

new functions

getCurColorRgba - Return array {r : var, g : var, b : var, a : var}
getCurAlpha - Return float alpha value 
setAlpha(newAlpha)

**Comment by forstjiri** [comment]
Wow, that was fast :+1: Thank you, job well done :)

**Comment by forstjiri** [comment]
Ok, just tried in my project and works great. I just changed updateInput method to change input value accordingly if alpha < 1

``` JS
function updateInput(){
        if (!input) return;

        if(a < 1) {
            input.value = 'rgba(' + rgb.r + ', ' + rgb.g + ', ' + rgb.b + ', ' + a.toFixed(2) + ')';
        }  else {
            input.value = hex;
        }

        if (inputColor) {
            if(hsv.v < 0.5){
                input.style.color = "#FFF";
            } else {
                input.style.color = "#000";
            }

            input.style.background = 'rgba(' + rgb.r + ', ' + rgb.g + ', ' + rgb.b + ', ' + a + ')';
        }
    }
```

**Comment by forstjiri** [comment]
I forked it, not sure if to make pull request since you had many useless space characters which my editor erased.

**Comment by NC22** [comment]
I'll look that, thanks.

**Comment by NC22** [comment]
https://github.com/NC22/HTML5-Color-Picker/blob/master/html5kellycolorpicker.js#L806

Your corrections in behavior added. And also added event 'updateinput' for overload private updateInput function if some other behavior is needed.
And yep, I forgot about this useless trailing whitespaces so have to erased them now too.
