### ISSUE TITLE
Circle disappearing in current Version of Chrome - Please verify

### ISSUE THREAD

**Issue by Thoba88** [NC22/HTML5-Color-Picker#12]
Hi, 

Chrome Version 103.0.5060.134 (Offizieller Build) (64-Bit).

On mouseup or mousemove the circle is disappearing in the current version of chrome maybe someone can check.
It worked well in former times/versions also it still works using Firefox.

![Colorpicker1](https://user-images.githubusercontent.com/36896088/181995581-9693cb55-cb09-4e2c-a37c-29eded92f45c.png)
![Colorpicker2](https://user-images.githubusercontent.com/36896088/181995583-1f89ed34-0306-479d-8829-72577004bfbc.png)

**Comment by NC22** [comment]
@Thoba88 

Hi. any ideas how to reproduce that in examples ? 

Tried to move mouse \ scroll ui elements, but no any luck in current Chrome version. may be you mean something else

https://disk.yandex.ru/d/DQboPS5S6oLz-Q

**Comment by Thoba88** [comment]
Hi
just found out that it only happens on
  method : 'triangle'

without alpha_slider. If you have triangle and alpha slider it doesnt disappear.

**Comment by NC22** [comment]
@Thoba88 you have this problem on demo pages of project too ? may be you share some of your example? this page is randomise them https://nc22.github.io/KellyC-Color-Picker/examples/test_create_and_destroy.html and I tried any variants include without sliders too

**Comment by Thoba88** [comment]
![image](https://user-images.githubusercontent.com/36896088/182032681-9f97faac-b809-430c-b276-abbc1f526803.png)

**Comment by Thoba88** [comment]
https://user-images.githubusercontent.com/36896088/182034437-80b58f54-d8e8-4d80-bd7b-9533c67b1dac.mp4

**Comment by Thoba88** [comment]
on mousedown the selection rectangle the circle comes back but on mouseup or mousemove it disappears again

**Comment by NC22** [comment]
@Thoba88 it was only gpu rendering issue, so I didnt notice it until changed global browser setting to GPU rendering. Should be fixed now

**Comment by Thoba88** [comment]
Yes works. Great job man thanks 👍
