### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by flofriday** [NC22/HTML5-Color-Picker#2]
The color-picker is a fine little tool and it would be nice if you could license it. This way I anyone could use your code without the fear of legal issues. I would recommend the [MIT license](https://de.wikipedia.org/wiki/MIT-Lizenz) wich gives the user almost all rights.

**Comment by flofriday** [comment]
Ok, found the license in the source.
But it would be still nice to the license in the README.md.
Thanks :)

**Comment by NC22** [comment]
Thanks for notice. I'll add license information.
