### ISSUE TITLE
No issue just a simple question

### ISSUE THREAD

**Issue by Allday3D** [NC22/HTML5-Color-Picker#9]
Thank you very much for this great color picker. Because I am just a noob in html, css and js I don't know how to get the current color showed. Like as example in the picture, how do I get the selected color showed under the text? And at the same time change the text "Select a Color" in a Hex format like "#dcdcdc"
![Capture7](https://user-images.githubusercontent.com/6654754/78556790-e466b400-780f-11ea-9b25-ecfd183a35a2.JPG)
Sorry for the noob question. Like you, English not my native language but I guess it's better to ask than to fiddling a long time without any luck. Any way thanks again.

**Comment by NC22** [comment]
Hi. Yep, thats pretty simple if I got what you trying to archive. I modified "test_attach_to_input" example, you can download it here https://catface.ru/userfiles/media/udata_1586218351_oskjtrqp.rar

**Comment by Allday3D** [comment]
Thanks for the example. I understand it a bit better. I only wanted to keep the multi input box to store the different colors (a button would be seen as submit and refreshes the page in my case). So the color showed are only at startup some basic RGB colors. The text I need, a HEX format, would be showed in a div.
`#ad3d-colorwheeldisplay{
  padding: 10px 10px 10px 40px;
  border-radius: 2px;
}

#ad3d-colorwheeldisplay::before{
  content: 'Select a Color';
  color: #ffffff;
  text-shadow: 0 0 4px #333333;
}`
I hoped it was easy to get the color value from your picker placed in my colorwheeldisplay!
Sorry if I was not clear enough about what I was trying to do.

**Comment by NC22** [comment]
> So the color showed are only at startup some basic RGB colors

Ah, ok, basically some thing similar can be found here

https://nc22.github.io/HTML5-Color-Picker/examples/test_one_colorpicer_and_multiple_inputs.html

so 

> The text I need, a HEX format, would be showed in a div

only thing you need is add div <div id='ad3d-colorwheeldisplay'></div>

and add in "change" event string that will update text in that div when colorwheel color changes

for example add before string "self.selectedInput.value" something like

document.getElementById('ad3d-colorwheeldisplay').innerText = self.getCurColorHex();

this will set text in div with current color picker color in hex format

**Comment by Allday3D** [comment]
Funny. That similar thing was/is the basic for my page. Seems I need learn a lot because it isn't working for me. Or the picker doesn't work anymore or I get other weird things. I Have placed a page on Git (here: https://github.com/Allday3D/LOL/tree/master/data/index.html) but start to think that it will not work for me or not yet at least. Need to learn.
Thanks anyway for your time.

**Comment by NC22** [comment]
> I Have placed a page on Git (here: https://github.com/Allday3D/LOL/tree/master/data/index.html) but start to think that it will not work for me or not yet at least. Need to learn.

Yes, in your case you also need to change css style because you use pseudo element to display text for some reason. So code will look like in pathes below (also I wasnt accurate in example in my prev comment - you need assign value to .innerText or .innerHTML of element to update it content)

https://github.com/NC22/LOL/commit/d12d338265bfb6cb9a27764bd7c9d08e4a577eaf
https://github.com/NC22/LOL/commit/5f5969dfa07ff30de280b2df62d3c381f121de0b

**Comment by Allday3D** [comment]
Wow. That starts to look like it. Thanks again for your time and wise lessons. I really appreciate this. Had never found: 

> you need assign value to .innerText or .innerHTML of element

May I ask if this:

> you use pseudo element to display text for some reason

isn't a good thing? Would it be better otherwise? Sorry for asking but maybe I learn something from it. Thanks again for everything.

**Comment by NC22** [comment]
> isn't a good thing? Would it be better otherwise? Sorry for asking but maybe I learn something from it. Thanks again for everything.

Depends on what you trying to achive

In common case you can put that text in div element and overwrite it on change color by assign value to innerText as I mention before

<div id="ad3d-colorwheeldisplay">Select a Color</div>

so css will be like 

#ad3d-colorwheeldisplay {
    background-color: rgb(220, 220, 220);
    color: #ffffff;
    text-shadow: 0 0 4px #333333;
}

and dont need "before" css pseudo element. Later if you need you can add classes to this div element in javascript like I did with "assigned" and change css for different cases like here https://github.com/NC22/LOL/commit/d12d338265bfb6cb9a27764bd7c9d08e4a577eaf

**Comment by Allday3D** [comment]
Ah. Ok. Think I got it. I have changed a few little things (again) and am happy so far with the result. The only thing I need to find out is the fact that the text and the color are only changed the first time after clicking on a input box! After that first time your color picker does a fantastic job. Thanks and sorry for the noob questions.
